function [new_prof_vals , str_params, num_params] = preprocessing()

    %% Import data from text file.
    % Script for importing data from the following text file:
    %
    %    loop_data_20170207-0210to0310.csv
    %
    % Auto-generated by MATLAB on 2017/02/11 15:24:31

    %% Initialize variables. (may need to change filename)
    
    file = 'Copy of loop_data_20170207-0210to0310';
    filename = 'Copy of loop_data_20170207-0210to0310.csv';
    delimiter = ',';
    startRow = 2;

    %% Format for each line of text:
    %   column1: text (%q)
    %	column2: text (%q)
    %   column3: double (%f)
    %	column4: double (%f)
    %   column5: double (%f)
    %	column6: text (%q)
    % For more information, see the TEXTSCAN documentation.
    formatSpec = '%q%q%f%f%f%q%[^\n\r]';

    %% Open the text file.
    fileID = fopen(filename,'r');

    %% Read columns of data according to the format.
    % This call is based on the structure of the file used to generate this
    % code. If an error occurs for a different file, try regenerating the code
    % from the Import Tool.
    dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

    %% Close the text file.
    fclose(fileID);

    %% Post processing for unimportable data.
    % No unimportable data rules were applied during the import, so no post
    % processing code is included. To generate code which works for
    % unimportable data, select unimportable cells in a file and regenerate the
    % script.

    %% Allocate imported array to column variable names
    time_stamp = dataArray{:, 1};
    loop_id = dataArray{:, 2};
    sample_period = dataArray{:, 3};
    profile_length = dataArray{:, 4};
    max_detuning = dataArray{:, 5};
    profile_values = dataArray{:, 6};


    %% Clear temporary variables
    clearvars filename delimiter startRow formatSpec fileID dataArray ans;
    
    %% Use the previus code to convert the profile values into something more useable
    new_prof_vals = {length(profile_values)};
    for i = 1:length(profile_values)

        profile  = profile_values{i};
        profile  = regexprep(profile,'[','');
        profile  = regexprep(profile,']','');
        profile  = regexprep(profile,'''','');
        profile  = regexprep(profile,' '    , '');
        profile = strsplit(profile,',');
        result = cellfun(@str2num, profile, 'UniformOutput', false);
        result = cell2mat(result);
        new_prof_vals{i} = result;
    end
    
    %% Demonstration (all data starts from 1 now too)
    %  most of this should be in a more usuable format now    
    str_params = [time_stamp, loop_id];
    num_params = [sample_period, profile_length, max_detuning];
    
    save(file, 'new_prof_vals', 'str_params','num_params');
    
end
    



